FROM python:3.7-buster

RUN apt-get update

COPY requirements.txt /home/Morozov/requirements.txt

RUN pip install -r /home/Morozov/requirements.txt

RUN pip install dask distributed --upgrade

WORKDIR /home/Morozov

RUN mkdir /home/Morozov/cachedir

COPY . .

CMD python3 Bimodal.py && python3 -c "from utils import upload; upload()"